# **REPRODUCIBLE NORMALIZATION PROBLEM**

In [ ]:
import numpy as np

In [ ]:
np.random.seed(2112)

In [ ]:
X = np.random.randint(10, 101, size=(5, 5))
X

array([[48, 11, 15, 67, 21],
       [11, 41, 13, 66, 24],
       [71, 79, 53, 67, 70],
       [77, 35, 91, 19, 96],
       [35, 54, 37, 41, 17]])

In [ ]:
x_bar = np.mean(X)
x_bar

np.float64(46.36)

In [ ]:
sigma = np.std(X)
sigma

np.float64(25.864075471588002)

In [ ]:
X_normalized = (X - x_bar)/sigma
X_normalized

array([[ 0.06340841, -1.36714726, -1.2124926 ,  0.79801809, -0.98051059],
       [-1.36714726, -0.20723725, -1.28981993,  0.75935442, -0.86451959],
       [ 0.95267275,  1.26198209,  0.25672675,  0.79801809,  0.91400909],
       [ 1.18465476, -0.43921926,  1.72594609, -1.05783793,  1.91926443],
       [-0.43921926,  0.29539042, -0.36189192, -0.20723725, -1.13516526]])

In [ ]:
np.std(X_normalized)

np.float64(0.9999999999999999)

In [ ]:
np.mean(X_normalized)

np.float64(0.0)

In [ ]:
np.save('X_normalized.npy', X_normalized)

# **CUBES DIVISIBLE BY 4 PROBLEM**

In [17]:
C = np.arange(1, 101)
C.resize(10, 10)
C

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [18]:
div_by_4 = C[C % 4 == 0]
C

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [19]:
div_by_4 = C[C % 4 == 0]
div_by_4

array([  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,
        56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

In [20]:
div_by_4.size

25

In [21]:
np.save('div_by_4.npy', div_by_4)

# **ABOVE-MEAN SQUARES PROBLEM**

In [22]:
S = (np.arange(1, 37) ** 2).reshape(6, 6)
S

array([[   1,    4,    9,   16,   25,   36],
       [  49,   64,   81,  100,  121,  144],
       [ 169,  196,  225,  256,  289,  324],
       [ 361,  400,  441,  484,  529,  576],
       [ 625,  676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225, 1296]])

In [23]:
S_mean = np.mean(S)
S_mean

np.float64(450.1666666666667)

In [24]:
above_mean = S[S > S_mean]
above_mean

array([ 484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296])

In [25]:
above_mean.size

15

In [26]:
np.save('above_mean.npy', above_mean)